# basic options
title: Miguel Gonzalez-Bolívar
author: Miguel Gonzalez-Bolivar
email: miguel-angel.gonzalez-boliv@hdr.mq.edu.au
description: PhD student at Macquarie University 
#twitter_username: jekyllrb
github_username:  miguelglezb

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight




