# basic options
title: Miguel Gonzalez astrosite
author: Miguel Gonzalez-Bolivar
email: miguel-angel.gonzalez-boliv@hdr.mq.edu.au
description: PhD Astro projects site 
#twitter_username: jekyllrb
github_username:  miguelglezb

# Build settings
markdown: kramdown
theme: minima

<iframe width="560" height="315" src="https://www.youtube.com/embed/hpwJE5DEk7U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
